// <auto-generated />
using System;
using JTExpress.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JTExpress.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515035249_AddUserAuthentication")]
    partial class AddUserAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JTExpress.Api.Data.BranchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Ayala Ave, Makati City",
                            Hours = "Mon–Sat 8AM–6PM",
                            Latitude = 14.5547,
                            Longitude = 121.0244,
                            Name = "J&T Express — Makati",
                            Phone = "(02) 8123-4001",
                            Region = "Metro Manila"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Quezon Ave, QC",
                            Hours = "Mon–Sat 8AM–6PM",
                            Latitude = 14.676,
                            Longitude = 121.0437,
                            Name = "J&T Express — Quezon City",
                            Phone = "(02) 8123-4002",
                            Region = "Metro Manila"
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 Colon St, Cebu City",
                            Hours = "Mon–Sat 8AM–6PM",
                            Latitude = 10.296900000000001,
                            Longitude = 123.9016,
                            Name = "J&T Express — Cebu",
                            Phone = "(032) 412-3001",
                            Region = "Visayas"
                        },
                        new
                        {
                            Id = 4,
                            Address = "22 Ilustre St, Davao City",
                            Hours = "Mon–Sat 8AM–6PM",
                            Latitude = 7.0731000000000002,
                            Longitude = 125.61279999999999,
                            Name = "J&T Express — Davao",
                            Phone = "(082) 227-3001",
                            Region = "Mindanao"
                        },
                        new
                        {
                            Id = 5,
                            Address = "100 MacArthur Hwy, San Fernando",
                            Hours = "Mon–Sat 8AM–6PM",
                            Latitude = 15.0794,
                            Longitude = 120.62,
                            Name = "J&T Express — Pampanga",
                            Phone = "(045) 961-3001",
                            Region = "Luzon"
                        },
                        new
                        {
                            Id = 6,
                            Address = "55 Iznart St, Iloilo City",
                            Hours = "Mon–Sat 8AM–6PM",
                            Latitude = 10.696899999999999,
                            Longitude = 122.56399999999999,
                            Name = "J&T Express — Iloilo",
                            Phone = "(033) 335-3001",
                            Region = "Visayas"
                        });
                });

            modelBuilder.Entity("JTExpress.Api.Data.RateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FirstKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("SucceedingKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstKg = 89m,
                            SucceedingKg = 19m,
                            Zone = "Metro Manila"
                        },
                        new
                        {
                            Id = 2,
                            FirstKg = 120m,
                            SucceedingKg = 29m,
                            Zone = "Luzon"
                        },
                        new
                        {
                            Id = 3,
                            FirstKg = 150m,
                            SucceedingKg = 39m,
                            Zone = "Visayas"
                        },
                        new
                        {
                            Id = 4,
                            FirstKg = 150m,
                            SucceedingKg = 39m,
                            Zone = "Mindanao"
                        },
                        new
                        {
                            Id = 5,
                            FirstKg = 180m,
                            SucceedingKg = 49m,
                            Zone = "Island Provinces"
                        });
                });

            modelBuilder.Entity("JTExpress.Api.Data.ServiceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PriceLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Next-day delivery within Metro Manila.",
                            Icon = "Express",
                            Name = "Express Delivery",
                            PriceLabel = "PHP 89+"
                        },
                        new
                        {
                            Id = 2,
                            Description = "2-5 business days to any province nationwide.",
                            Icon = "Parcel",
                            Name = "Standard Delivery",
                            PriceLabel = "PHP 60+"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Buyer pays only upon receiving the parcel.",
                            Icon = "COD",
                            Name = "Cash on Delivery",
                            PriceLabel = "Free"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Specialized handling for oversized and heavy items.",
                            Icon = "Cargo",
                            Name = "Bulky Cargo",
                            PriceLabel = "Custom"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Picked up and delivered to your exact address.",
                            Icon = "Door",
                            Name = "Door-to-Door",
                            PriceLabel = "PHP 79+"
                        });
                });

            modelBuilder.Entity("JTExpress.Api.Data.TrackingEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackingResultEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrackingResultEntityId");

                    b.ToTable("TrackingEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "May 13 03:00 PM",
                            Location = "Makati City",
                            Status = "Delivered",
                            TrackingResultEntityId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = "May 13 09:00 AM",
                            Location = "Makati Hub",
                            Status = "Out for Delivery",
                            TrackingResultEntityId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = "May 12 11:00 PM",
                            Location = "Makati Hub",
                            Status = "Arrived at Hub",
                            TrackingResultEntityId = 1
                        },
                        new
                        {
                            Id = 4,
                            Date = "May 12 06:00 AM",
                            Location = "Quezon City",
                            Status = "Parcel Picked Up",
                            TrackingResultEntityId = 1
                        },
                        new
                        {
                            Id = 5,
                            Date = "May 14 08:00 AM",
                            Location = "Manila Sorting Center",
                            Status = "In Transit",
                            TrackingResultEntityId = 2
                        },
                        new
                        {
                            Id = 6,
                            Date = "May 13 04:00 PM",
                            Location = "Cebu City",
                            Status = "Parcel Picked Up",
                            TrackingResultEntityId = 2
                        },
                        new
                        {
                            Id = 7,
                            Date = "May 15 07:00 AM",
                            Location = "Davao Hub",
                            Status = "Out for Delivery",
                            TrackingResultEntityId = 3
                        },
                        new
                        {
                            Id = 8,
                            Date = "May 14 10:00 PM",
                            Location = "Davao Hub",
                            Status = "Arrived at Hub",
                            TrackingResultEntityId = 3
                        },
                        new
                        {
                            Id = 9,
                            Date = "May 14 02:00 PM",
                            Location = "Manila Hub",
                            Status = "In Transit",
                            TrackingResultEntityId = 3
                        });
                });

            modelBuilder.Entity("JTExpress.Api.Data.TrackingResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstimatedDelivery")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrackingResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentLocation = "Makati City",
                            EstimatedDelivery = "May 13, 2025",
                            Recipient = "Maria Santos",
                            Sender = "Juan dela Cruz",
                            Status = "Delivered",
                            TrackingNumber = "JT123456789PH"
                        },
                        new
                        {
                            Id = 2,
                            CurrentLocation = "Manila Sorting Center",
                            EstimatedDelivery = "May 16, 2025",
                            Recipient = "Ana Lim",
                            Sender = "Pedro Reyes",
                            Status = "In Transit",
                            TrackingNumber = "JT987654321PH"
                        },
                        new
                        {
                            Id = 3,
                            CurrentLocation = "Davao Hub",
                            EstimatedDelivery = "May 15, 2025",
                            Recipient = "Rose Villanueva",
                            Sender = "Carlo Mendoza",
                            Status = "Out for Delivery",
                            TrackingNumber = "JT555000111PH"
                        });
                });

            modelBuilder.Entity("JTExpress.Api.Data.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JTExpress.Api.Data.TrackingEventEntity", b =>
                {
                    b.HasOne("JTExpress.Api.Data.TrackingResultEntity", null)
                        .WithMany("Timeline")
                        .HasForeignKey("TrackingResultEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JTExpress.Api.Data.TrackingResultEntity", b =>
                {
                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
